### ISSUE TITLE
 php public/index.php humus amqp consumer demo-consumer is crashing

### ISSUE THREAD

**Issue by philippeback** [prolic/HumusAmqpDemoModule#1]
Looks like the thing gets n Event and not an AMQPEnvelope

Things like :+1: 
    php public/index.php humus amqp list-exchanges
    php public/index.php humus amqp setup-fabric

do work.
RabbitMQ works ok on the box, as are the other extensions.
All 

Catchable fatal error: Argument 1 passed to HumusAmqpDemoModule\Demo\EchoCallback::__invoke() must be an instance of AMQPEnvelope, instance of Zend\EventManager\Event given in /home/philippeback/workspace/testzf2/vendor/prolic/humus-amqp-demo-module/src/HumusAmqpDemoModule/Demo/EchoCallback.php on line 14

Call Stack:
    0.0002     226456   1. {main}() /home/philippeback/workspace/testzf2/public/index.php:0
    0.0773    5498928   2. Zend\Mvc\Application->run() /home/philippeback/workspace/testzf2/public/index.php:25
    0.0790    5530160   3. Zend\EventManager\EventManager->trigger() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-mvc/src/Application.php:314
    0.0790    5530240   4. Zend\EventManager\EventManager->triggerListeners() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:205
    0.0793    5537408   5. call_user_func() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:444
    0.0793    5537976   6. Zend\Mvc\DispatchListener->onDispatch() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:444
    0.0849    6087264   7. HumusAmqpModule\Controller\ConsumerController->dispatch() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-mvc/src/DispatchListener.php:93
    0.1011    6750208   8. HumusAmqpModule\Consumer->consume() /home/philippeback/workspace/testzf2/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Controller/ConsumerController.php:83
    0.1017    6753712   9. HumusAmqpModule\Consumer->handleDelivery() /home/philippeback/workspace/testzf2/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php:202
    0.1018    6754664  10. Zend\EventManager\EventManager->trigger() /home/philippeback/workspace/testzf2/vendor/prolic/humus-amqp-module/src/HumusAmqpModule/Consumer.php:241
    0.1018    6755288  11. Zend\EventManager\EventManager->triggerListeners() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:205
    0.1022    6762800  12. call_user_func() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:444
    0.1022    6762872  13. HumusAmqpDemoModule\Demo\EchoCallback->__invoke() /home/philippeback/workspace/testzf2/vendor/zendframework/zend-eventmanager/src/EventManager.php:444

**Comment by prolic** [comment]
Hi. Thanks for the feedback. This is currently a dependency problem. I hope to find time to work on it the next two weeks.
If you use tagged versions, the problem should disappear.

**Comment by philippeback** [comment]
Thx, will have a look tomorrow.

Now, for the time being I moved to

"videlalvaro/php-amqplib": "2.5.*"

with a bit of Zend\Config

Which isn't as cool as what you have but there are many components in your
module and demo and it is hard to see how the patterns do work.

I had a hard look on the module (including the class resolution story where
there is that huge mapping) and the plugins but the plugins were a bit
complicated to figure out.

I'd love to see more simple examples.

For sure a working demo will help me.

The console tools are neat!

**Comment by prolic** [comment]
php-amqplib is on the roadmap to get integrated in case the amqp extension is missing. I'll let you know, when an update is available.
Thanks for the input.

**Comment by prolic** [comment]
@philippeback fixed!

new bugfix-release v0.1.1
